# APinchofDill config for mkdocs documentation site generator

site_name: Oceanology Docs
site_url: https://galidar.github.io/oceanology-docs

# Repository
repo_name: Galidar/oceanology-docs
repo_url: https://github.com/Galidar/oceanology-docs
edit_uri: ""

# Plugins
plugins:
  - offline
  - glightbox
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
theme:
  favicon: ./assets/images/logo.jpg
  logo: ./assets/images/logo.jpg
  name: material
  custom_dir: overrides
  palette:
    primary: black
    scheme: slate
    # Palette toggle for dark mode
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    # # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode
  features:
    - navigation.path
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes

# Page navigation
nav:
  - Home: index.md
  - Getting started:
    - Installation: ./getting-started/installation.md
    - Setup: ./getting-started/setup.md
    - Features:
      - Audio: ./getting-started/features/audio-system.md
      - Buoyancy: ./getting-started/features/buoyancy-configuration.md
      - Infinite: ./getting-started/features/infinite-or-not-infinite.md
      - QuadTree: ./getting-started/features/quadtree.md
      - RVT Manager: ./getting-started/features/rvt-heightmap-actor-manager.md
      - Swimming: ./getting-started/features/swimming-configuration.md
      - Water Volume: ./getting-started/features/water-volume.md
  - Tutorials:
    - Oceanology + Easy Survival RPG: ./tutorials/easy-survival-rpg.md
    - RVT Multiple landscapes: ./tutorials/rvt-multiple-landscapes.md
    - Boat Buoyancy: ./tutorials/boat-buoyancy.md
    - RVT Setup: ./tutorials/rvt-setup.md
    - Ultra Dynamic Sky: ./tutorials/oc-uds.md
    - WorldScape: ./tutorials/oc-worldscape.md
  - Intergrations:
    - ./intergrations/index.md
    - WaterInteractionPlugin: ./intergrations/WaterInteractionPlugin.md
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra:
  annotate:
    json: [.s2]
  version:
    provider: mike
extra_css:
  - ./assets/stylesheets/extra.css